#!/usr/bin/env bash
# script to report information about server domains
# shellcheck disable=SC2086

# Function to display subdomain information
display_info() {
    local subdomain="$1"
    local domain="$2"
    local record_type="$3"
    local destination="$4"
    echo "The subdomain $subdomain is a $record_type record and points to $destination"
}

# Check if both domain and subdomain are provided
if [ $# -eq 2 ]; then
    subdomain="$2"
    domain="$1"

    # Use dig command to get DNS information and awk to parse it
    dns_info=$(dig "$subdomain.$domain" | awk '/ANSWER SECTION:/ {getline; print}')

    # Extract record type and destination IP
    record_type=$(echo "$dns_info" | awk '{print $4}')
    destination=$(echo "$dns_info" | awk '{print $5}')

    # Display subdomain information
    display_info "$subdomain" "$domain" "$record_type" "$destination"
elif [ $# -eq 1 ]; then
    # If only domain is provided, display information for default subdomains
    domain="$1"
    subdomains=("www" "lb-01" "web-01" "web-02")

    for subdomain in "${subdomains[@]}"; do
        dns_info=$(dig "$subdomain.$domain" | awk '/ANSWER SECTION:/ {getline; print}')
        record_type=$(echo "$dns_info" | awk '{print $4}')
        destination=$(echo "$dns_info" | awk '{print $5}')
        display_info "$subdomain" "$domain" "$record_type" "$destination"
    done
else
    echo "Usage: $0 domain [subdomain]"
fi
