#!/usr/bin/env bash
# Install nginx web server

sudo service nginx start

echo "server {
    listen 80;
    server_name _;

    location / {
        root /var/www/html;
        index index.html;
        add_header Content-Type text/html;
        echo 'Hello World!';
    }
}" | sudo tee /etc/nginx/sites-available/default > /dev/null

sudo service nginx reload
sudo update-rc.d nginx enable
if pgrep nginx > /dev/null
then
    echo "Nginx is running."
else
    echo "Nginx is not running. Something went wrong."
fi
