#!/usr/bin/env bash
# Create a custom 404 page
sudo sh -c "echo 'Ceci n'\''est pas une page' > /var/www/html/404.html"

# Add a location block for the 404 page to the Nginx configuration file
config="/etc/nginx/sites-available/default"
sudo sed -i '/^}$/i \ \n\tlocation @404 {return 404 "/404.html";}' $config

# Change the 404 error page location
sudo sed -i 's/=404/@404/g' $config

# Restart Nginx
sudo service nginx restart
