#!/usr/bin/env bash
# Double the number of webservers

sudo apt-get -y update
sudo apt-get -y install nginx

# Add the X-Served-By header to the root location only
config="/etc/nginx/sites-available/default"
sudo sed -i "0,/location \/ {/s/location \/ {/&\n\t\tadd_header X-Served-By '$HOSTNAME';/" $config

# Create the index.nginx-debian.html file
sudo sh -c "echo 'Hello World!' > /var/www/html/index.nginx-debian.html"

# Add the redirect_me and 404 locations
sudo sed -i '/^}$/i \ \n\tlocation \/redirect_me {return 301 https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4;}' $config
sudo sed -i '/^}$/i \ \n\tlocation @404 {return 404 "Ceci n'\''est pas une page\\n";}' $config

# Change the 404 error page location
sudo sed -i 's/=404/@404/g' $config

# Restart Nginx
sudo service nginx restart
