#!/usr/bin/env bash
# Double the number of webservers
sudo apt-get -y update
sudo apt-get -y install nginx

# Configure Nginx to add a custom HTTP response header
config="/etc/nginx/sites-available/default"
sudo sed -i "0,/location \/ {/s/location \/ {/&\n\t\tadd_header X-Served-By '$HOSTNAME';/" $config

# Restart Nginx
sudo service nginx restart
