#!/usr/bin/env bash
# configures a server to listening on port 80 of all server's active IPv4 IPs

# REMOVE THE DEAULT CONGIURATION FILE
rm /etc/nginx/sites-enabled/default

# CONDIGURE NGINX TO LISTEN ON PORT 80 FOR ALL ACTIVE IP4V
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
# RESTART NGINX
sudo service nginx restart
