#!/usr/bin/env bash
# publick key

SSH_PUBLIC_KEY="ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDNdtrNGtTXe5Tp1EJQop8mOSAuRGLjJ6DW4PqX4wId/Kawz35ESampIqHSOTJmbQ8UlxdJuk0gAXKk3Ncle4safGYqM/VeDK3LN5iAJxf4kcaxNtS3eVxWBE5iF3FbIjOqwxw5Lf5sRa5yXxA8HfWidhbIG5TqKL922hPgsCGABIrXRlfZYeC0FEuPWdr6smOElSVvIXthRWp9cr685KdCI+COxlj1RdVsvIo+zunmLACF9PYdjB2s96Fn0ocD3c5SGLvDOFCyvDojSAOyE70ebIElnskKsDTGwfT4P6jh9OBzTyQEIS2jOaE5RQq4IB4DsMhvbjDSQrP0MdCLgwkN"


REMOTE_SERVER="8.8.8.8"
REMOTE_USER="ubuntu"

SSH_DIR="/home/$REMOTE_USER/.ssh"

ssh "$REMOTE_USER@$REMOTE_SERVER" "mkdir -p $SSH_DIR"

echo "$SSH_PUBLIC_KEY" | ssh "$REMOTE_USER@$REMOTE_SERVER" "cat >> $SSH_DIR/authorized_keys"

ssh "$REMOTE_USER@$REMOTE_SERVER" "chmod 700 $SSH_DIR && chmod 600 $SSH_DIR/authorized_keys"

echo "SSH public key added to the server. You can now connect using the 'ubuntu' user."
