#!/usr/bin/env bash
# configured to use the private key ~/.ssh/school
# configured to refuse to authenticate using a password
Host *
    SendEnv LANG LC_*
    HashKnownHosts yes
    GSSAPIAuthentication yes
    GSSAPIDelegateCredentials no
    IdentityFile ~/.ssh/school
    PasswordAuthentication no
